version: "1"
services:
  # 1. EventFlow Control Plane (Spring Boot API)
  - type: web
    name: eventflow-control-plane
    runtime: docker
    dockerfilePath: services/control-plane/Dockerfile
    dockerContext: services/control-plane
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: eventflow-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: eventflow-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: eventflow-db
          property: password
      - key: QUEUE_MODE
        value: POSTGRES
      - key: MINIO_URL
        value: http://eventflow-minio:9000
      - key: MINIO_ACCESS_KEY
        value: eventflow
      - key: MINIO_SECRET_KEY
        value: eventflow123
      - key: MINIO_BUCKET
        value: functions

  # 2. EventFlow Function Worker (Node.js)
  - type: web
    name: eventflow-worker
    runtime: docker
    dockerfilePath: services/worker/Dockerfile
    dockerContext: services/worker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eventflow-db
          property: connectionString
      - key: DATABASE_SSL
        value: "true"
      - key: QUEUE_MODE
        value: POSTGRES
      - key: CACHE_MODE
        value: DB
      - key: MINIO_ENDPOINT
        value: eventflow-minio
      - key: MINIO_PORT
        value: "9000"
      - key: MINIO_USE_SSL
        value: "false"
      - key: MINIO_ACCESS_KEY
        value: eventflow
      - key: MINIO_SECRET_KEY
        value: eventflow123
      - key: MINIO_BUCKET
        value: functions

  # 3. EventFlow Object Storage (MinIO)
  - type: web
    name: eventflow-minio
    runtime: docker
    dockerfilePath: services/minio/Dockerfile
    dockerContext: services/minio
    plan: free
    envVars:
      - key: PORT
        value: "9001" # Tells Render to route public traffic to the Console port
      - key: MINIO_ROOT_USER
        value: eventflow
      - key: MINIO_ROOT_PASSWORD
        value: eventflow123

databases:
  # PostgreSQL Database (Render's Native Free Database)
  - name: eventflow-db
    databaseName: eventflow
    user: eventflow
    plan: free
