spring.application.name=control-plane
spring.datasource.url=jdbc:postgresql://localhost:5432/eventflow
spring.datasource.username=eventflow
spring.datasource.password=eventflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.devtools.restart.enabled=true